version: "3.7"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on: []
    image: skandha_sample_bulky_frontend
    ports:
      - 3000:3000
    volumes: []
