version: "3.7"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: sleep infinity
    depends_on: []
    image: skandha_sample_bulky_frontend_dev
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app/src
